// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using advertising.Data;

namespace advertising.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20210415075151_AddedPersonalId")]
    partial class AddedPersonalId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("advertising.Models.Ad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ad_ad_id");

                    b.Property<int>("AdCost")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ad_ad_cost");

                    b.Property<long>("AdvertiserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ad_fk_advertiser_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ad_content");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ad_headline");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ad_price");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiserId");

                    b.ToTable("tbl_ads");
                });

            modelBuilder.Entity("advertising.Models.Advertiser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("adv_advertiser_id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("adv_distribution_city");

                    b.Property<string>("DistributionAddress")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("adv_distribution_address");

                    b.Property<string>("Firstname")
                        .HasColumnType("TEXT")
                        .HasColumnName("adv_first_name");

                    b.Property<string>("InvoiceAddress")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("adv_invoice_address");

                    b.Property<string>("InvoiceCity")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("adv_invoice_city");

                    b.Property<string>("InvoiceZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("adv_invoice_zip_code");

                    b.Property<string>("Lastname")
                        .HasColumnType("TEXT")
                        .HasColumnName("adv_last_name");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("TEXT")
                        .HasColumnName("adv_organization_name");

                    b.Property<long?>("OrganizationNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("adv_organization_number");

                    b.Property<long?>("PersonalId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("adv_personal_id");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("adv_phone_number");

                    b.Property<long?>("SubscriberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("adv_subscriber_id");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("adv_distribution_zip_code");

                    b.Property<bool>("isOrganization")
                        .HasColumnType("INTEGER")
                        .HasColumnName("adv_is_organization");

                    b.HasKey("Id");

                    b.ToTable("tbl_advertisers");
                });

            modelBuilder.Entity("advertising.Models.Ad", b =>
                {
                    b.HasOne("advertising.Models.Advertiser", "Advertiser")
                        .WithMany("Ads")
                        .HasForeignKey("AdvertiserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertiser");
                });

            modelBuilder.Entity("advertising.Models.Advertiser", b =>
                {
                    b.Navigation("Ads");
                });
#pragma warning restore 612, 618
        }
    }
}
